yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField('Название группы', max_length=200)
    slug = models.SlugField(
        'Поле slug для составления ссылки',
        max_length=200,
        unique=True
    )
    description = models.TextField('Описание')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Текст нового поста'
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата создания',
        auto_now_add=True,
    )
    update_date = models.DateTimeField(
        verbose_name='Дата редактирования',
        auto_now=True
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
    )
    group = models.ForeignKey(
        Group,
        models.SET_NULL,
        verbose_name='Группа',
        blank=True,
        null=True,
        related_name='posts',
        help_text='Группа, к которой будет относиться пост',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        help_text='Изображение поста',
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='comments',
        help_text='Комментарий к посту'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='comments',
        help_text='Автор комментария'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария'
    )
    pub_date = models.DateTimeField(
        'Дата создания',
        auto_now_add=True,
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Подписчик',
        related_name='follower',
        help_text='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Подписки',
        related_name='following',
        help_text='Подписки'
    )

    class Meta:
        ordering = ['-user']
        verbose_name = 'Подписки'
        verbose_name_plural = 'Подписки'

    def __str__(self):
        return self.user.username

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
# -*- coding: cp1251 -*-
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Group, User, Follow
from .forms import PostForm, CommentForm

POSTS_PER_PAGE = 10


def paginate_in_view(queryset, request):
    page_number = request.GET.get('page')
    paginator = Paginator(queryset, POSTS_PER_PAGE)
    page_obj = paginator.get_page(page_number)

    return {
        'page_obj': page_obj,
        'post_count': queryset.count()
    }


def index(request):
    template = 'posts/index.html'
    posts = Post.objects.all()
    pagination_context = paginate_in_view(
        posts,
        request,
    )
    context = {
        'page_obj': pagination_context['page_obj'],
        'index': True,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    pagination_context = paginate_in_view(
        posts,
        request,
    )
    context = {
        'group': group,
        'page_obj': pagination_context['page_obj'],
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    following = False
    user = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author_id=user.id)
    pagination_context = paginate_in_view(
        posts,
        request,
    )

    if request.user.is_authenticated:
        followers = Follow.objects.filter(
            author_id=user.id, user_id=request.user)
        if followers:
            following = True

    context = {
        'page_obj': pagination_context['page_obj'],
        'post_count': pagination_context['post_count'],
        'username': user,
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    comment = post.comments.all()
    posts_count = Post.objects.filter(author=post.author).count()
    title = post.text[0:30]
    context = {
        'post': post,
        'title': title,
        'posts_count': posts_count,
        'form': form,
        'comments': comment,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    context = {
        'form': form,
    }
    if not form.is_valid():
        return render(request, template, context)
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', username=request.user)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    template = 'posts/create_post.html'
    return_view = 'posts:post_detail'
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )
    is_edit = True
    context = {
        'form': form,
        'is_edit': is_edit,
        'post_id': post_id,
    }
    if not request.user == post.author:
        return redirect(return_view, post_id=post.pk)
    if not form.is_valid():
        return render(request, template, context)
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect(return_view, post_id=post.pk)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    authors = Follow.objects.filter(user=request.user).values_list(
        'author_id', flat=True
    )
    posts = Post.objects.filter(author_id__in=authors)
    pagination_context = paginate_in_view(
        posts,
        request,
    )

    context = {
        'page_obj': pagination_context['page_obj'],
        'post_count': pagination_context['post_count'],
        'follow': True,
    }

    return render(request, template, context)


@login_required
def profile_follow(request, username):
    following = get_object_or_404(User, username=username)
    current_user = request.user
    if current_user != following:
        Follow.objects.get_or_create(user=current_user, author=following)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    current_user = request.user
    following = get_object_or_404(User, username=username)
    Follow.objects.filter(author=following, user=current_user).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %} 
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить запись
  {% endif %}
{{ title }} {% endblock %}
{% block content %}
  <main>
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
		    {{ title }}             
          </div>
          <div class="card-body"> 
            {% load user_filters %} {# Загружаем фильтры #}
            {% if form.errors %}
              {% for field in form %} 
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}
		    {% if is_edit %}
              <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_edit' post_id %}">
		    {% else %}
	          <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_create' %}">
		    {% endif %}
            {% csrf_token %}
            {% for field in form %} 
              <div class="form-group row my-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                </label>
                {{ field|addclass:'form-control' }} 
                  {% if field.help_text %}
				    {% if is_edit %}
                      <small id="id_text-help" class="form-text text-muted">
                        Текст редактируемого поста
                      </small>					  
					{% else %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
					{% endif %}  
                  {% endif %}
              </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
			    {% if is_edit %}
                  Сохранить
				{% else %}
				  Добавить
				{% endif %}  
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %} Мои подписки {% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
	<article>
	  {% include 'posts/includes/author.html' %}
      {% include 'posts/includes/post.html' %}
	</article>
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} {{ group.title }} {% endblock %}
{% block content %}
  <div class="container">
    <h1>Записи сообщества: {{ group.title }}</h1>
    <p>{{ group.description }}</p>
    {% for post in page_obj %}
	<article>
	  {% include 'posts/includes/author.html' %}
      {% include 'posts/includes/post.html' %}
	</article>
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}  
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %} Последние обновления на сайте {% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
{% load cache %}
  <div class="container">
    <h1>Последние обновления на сайте</h1>
	{% cache 20 index_page page_obj %}
    {% for post in page_obj %}
	<article>
	  {% include 'posts/includes/author.html' %}
      {% include 'posts/includes/post.html' %}
	</article>
    {% endfor %}
	{% endcache %}
    {% include 'posts/includes/paginator.html' %}
  </div>  
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} Пост {{title}} {% endblock %}
{% block content %}
  <main>
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
		  <li class="list-group-item">
            Дата редактирования: {{ post.update_date|date:"d E Y" }}
          </li>
          <li class="list-group-item">
            Группа:
			{% if post.group.slug %}
              {{post.group.slug}}
		      <a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы
              </a>
		    {% else %}
              <span style="color:red"> 
                Группа не назначена для данной записи! 
              </span>
		    {% endif %}
          </li>
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{posts_count}}</span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author %}">
              все посты пользователя
            </a>
          </li>
        </ul>
	  </aside>
      <article class="col-12 col-md-9">
	    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text }}</p>
		{% if post.author == request.user %}
		  <a class="btn btn-primary" 
		  href="{% url 'posts:post_edit' post.pk %}">
            редактировать запись
          </a>
		{% endif %}
		{% include 'posts/includes/post_comment.html' %}
      </article>
    </div> 
  </main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} Профайл пользователя {{ username.get_full_name }} {% endblock %}
{% block content %}
  <main>
  <div class="mb-5">
    <h1>Все посты пользователя {{ username.get_full_name }} </h1>
    <h3>Всего постов: {{ post_count }}</h3>
	{% if username != request.user %}
	  {% if following %}
	    <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' username %}" role="button"
        >
          Подписаться
        </a>
	  {% endif %}
   {% endif %}
   </div>
    {% for post in page_obj %}
      <article>
        {% include 'posts/includes/post.html' %}
      </article>
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}  
  </main>
{% endblock %}